exclude_paths:
  - '**/*.test.tsx'
engines:
  duplication:
    minTokenMatch: 120
    skipLexicalErrors: false
    ignoreLiterals: false
    ignoreIdentifiers: true
    ignoreAnnotations: false
    ignoreUsings: false
